#!/usr/bin/env python3

from Hako.Console.Kernel import Kernel

# To Do:
# Add aliasing to command option signatures
# Split loader stuff to its own class/tests?
# Write comments / look into python api docs / docblock
# Ability to prompt for user input in command
# Pretty printing / console print colors from commands, self.info, self.warn etc
Kernel(__file__).handle()